:spring_version: current
:toc:
:project_id: gs-rest-service
:icons: font
:source-highlighter: prettify

本教程教你通过Spring创建一个“`Hello, World`”REST 风格的Web服务。

== 你将会创建什么

你将会创建一个接收地址是`http://localhost:8080/greeting` HTTP Get请求的服务。
这个服务将会返回一个JSON格式的结果，如下所示：

====
[source,json]
----
{"id":1,"content":"Hello, World!"}
----
====

你可以通过链接字符串的参数`name`自定义这个请求的结果，内容如下：

====
[source,text]
----
http://localhost:8080/greeting?name=User
----
====

这个`name`参数会覆盖默认值`World`，然后显示在相应结果，结果如下所示：

====
[source,json]
----
{"id":1,"content":"Hello, User!"}
----
====

== 你需要什么

:java_version: 1.8
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]

[[scratch]]
== Starting with Spring Initialize

如果你使用Maven, 访问 https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.4.3.RELEASE&packaging=jar&jvmVersion=1.8&groupId=com.example&artifactId=rest-service&name=rest-service&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.rest-service&dependencies=web[Spring Initializr] 创建一个Spring Web新项目。

如果是选择Maven，对应的`pom.xml`文件如下所示:

====
[source,xml]
----
include::initial/pom.xml[]
----
====

如果你使用Gradle, 访问 https://start.spring.io/#!type=gradle-project&language=java&platformVersion=2.4.3.RELEASE&packaging=jar&jvmVersion=1.8&groupId=com.example&artifactId=rest-service&name=rest-service&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.rest-service&dependencies=web[Spring Initializr] 创建一个Spring Web新项目。

如果是选择Gradle，对应的`build.gradle`文件如下所示:

====
[source,text]
----
include::initial/build.gradle[]
----
====

=== 手动初始化 (可选)

如果你更喜欢使用手动初始化，可以按照虾米的步骤进行：

. 访问 https://start.spring.io。
该服务引入应用程序所需的所有依赖项，并为您完成大部分设置工作。
. 选择Gradle或Maven以及你想要使用的语言。本指南假设您选择了Java。
. 点击 *Dependencies* 并且选择*Spring Web*.
. 点击 *Generate（生成）*.
. 下载生成的ZIP文件，这个文件是按照你的选择生成的Web应用程序的压缩包。

注意: 如果您的IDE有Spring Initializr集成，您可以从您的IDE完成这个过程。

[[initial]]
== 创建一个资源表示类

现在你已经创建了一个项目，并且已经设置了构建系统，你可以开始创建你的web服务了。

首先考虑这个服务的交互。

这个服务处理`/greeting`的`GET`请求，在查询字符串中有一个可选参数`name`。这个`GET`请求需要返回的响应状态为`200 OK`，body内容为JSON格式的greeting，如下所示：
====
[source,json]
----
{
    "id": 1,
    "content": "Hello, World!"
}
----
====

 `id`字段是一个唯一标识符，`content`文本格式.

为了模型化表示欢迎内容，需要创建一个资源表示类，创建一个POJO类，包括需要的字段、构造函数、字段`id`和`content`的访问器，内容如下所示（`src/main/java/com/example/restservice/Greeting.java`）：


[source,java]
----
include::complete/src/main/java/com/example/restservice/Greeting.java[]
----

====
注意: 这个应用使用 https://github.com/FasterXML/jackson[Jackson JSON] 类库自动格式化`Greeting`实例为JSON。Jackson 已经默认包含到应用中。
====

== 创建一个资源控制器

在Spring构建RESTful web服务的方法中，HTTP请求需要通过一个控制器处理。 这些组件通过
https://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/web/bind/annotation/RestController.html[`@RestController`]注解标识，
下面列出的`GreetingController` (
`src/main/java/com/example/restservice/GreetingController.java`) 处理/greeting`来自的`GET` 请求，返回一个新的`Greeting`类实例：

====
[source,java]
----
include::complete/src/main/java/com/example/restservice/GreetingController.java[]
----
====

这个控制器非常简洁和简单，但是背后有很多的内幕，我们一步一步解析它。

`@GetMapping` 注解确保`/greeting`的GET请求指向方法`greeting()`。

注意: 还有其他HTTP谓语注解 (如: POST请求使用`@PostMapping` )， 这两个都是从`@RequestMapping`注解派生出来的，可以作为同义词使用  (如. `@RequestMapping(method=GET)`).

`@RequestParam`绑定查询字符串的参数`name`到方法`greeting()`的参数`name`。如果请求没有参数`name`则使用默认值`World`。
方法创建并返回了一个`Greeting`对象，`id`属性为`counter`的下一个值，`content`属性使用模板`template`和参数`name`格式化。

传统MVC控制器和REST风格web服务控制器的关键区别是控制器中HTTP响应体的创建方式，而不是依靠视图技术把数据在服务端通过HTML格式渲染。这个REST风格web服务控制器填充并返回一个`Greeting`对象，这个对象将作为JSON直接写入HTTP响应。

代码使用了Spring
https://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/web/bind/annotation/RestController.html[`@RestController`]
注解, 标记这个类是一个控制器并且每个方法返回一个领域对象而不是一个视图。这是包括`@Controller` 和
`@ResponseBody`的简写。

对象`Greeting` 必须被转换为JSON。感谢Spring的HTTP消息转换器支持，你不需要手动执行转换。因为
https://github.com/FasterXML/jackson[Jackson 2]已经在classpath, Spring的
https://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/http/converter/json/MappingJackson2HttpMessageConverter.html[`MappingJackson2HttpMessageConverter`]
自动选择它把`Greeting` 实例转换为JSON。

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/spring-boot-application-new-path.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_subhead.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_with_both.adoc[]

显示日志输出，服务应该在几秒钟内启动并运行。


== 测试这个服务

现在服务已经启动了, 打开链接 `http://localhost:8080/greeting`, 内容如下:

====
[source,json]
----
{"id":1,"content":"Hello, World!"}
----
====

通过查询字符串参数`name`访问`http://localhost:8080/greeting?name=User`。 注意`content`的内容从 `Hello, World!` 变为 `Hello, User!`, 如下所示:

====
[source,json]
----
{"id":2,"content":"Hello, User!"}
----
====
这个改变说明`@RequestParam`注解如预期工作。参数`name`默认值为`World`,但是可以通过查询字符串覆盖。
注意`id`属性从`1`变为`2`。 这个证明你在多次请求访问相同的`GreetingController`实例，并且它的`counter`字段按预期递增。

== 总结

恭喜! 你已经通过Spring 完成了一个REST风格的Web服务.

== 更多

以下指南可能也会有所帮助:

* https://spring.io/guides/gs/accessing-gemfire-data-rest/[Accessing GemFire Data with REST]
* https://spring.io/guides/gs/accessing-mongodb-data-rest/[Accessing MongoDB Data with REST]
* https://spring.io/guides/gs/accessing-data-mysql/[Accessing data with MySQL]
* https://spring.io/guides/gs/accessing-data-rest/[Accessing JPA Data with REST]
* https://spring.io/guides/gs/accessing-neo4j-data-rest/[Accessing Neo4j Data with REST]
* https://spring.io/guides/gs/consuming-rest/[Consuming a RESTful Web Service]
* https://spring.io/guides/gs/consuming-rest-angularjs/[Consuming a RESTful Web Service with AngularJS]
* https://spring.io/guides/gs/consuming-rest-jquery/[Consuming a RESTful Web Service with jQuery]
* https://spring.io/guides/gs/consuming-rest-restjs/[Consuming a RESTful Web Service with rest.js]
* https://spring.io/guides/gs/securing-web/[Securing a Web Application]
* https://spring.io/guides/tutorials/rest/[Building REST services with Spring]
* https://spring.io/guides/tutorials/react-and-spring-data-rest/[React.js and Spring Data REST]
* https://spring.io/guides/gs/spring-boot/[Building an Application with Spring Boot]
* https://spring.io/guides/gs/testing-restdocs/[Creating API Documentation with Restdocs]
* https://spring.io/guides/gs/rest-service-cors/[Enabling Cross Origin Requests for a RESTful Web Service]
* https://spring.io/guides/gs/rest-hateoas/[Building a Hypermedia-Driven RESTful Web Service]
* https://spring.io/guides/gs/circuit-breaker/[Circuit Breaker]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/footer.adoc[]
